from fastapi import APIRouter

from apps.compares.api.compare_averages_with_scenario import compare_averages_with_scenario_router
from apps.compares.api.compare_load_test_results_history import compare_load_test_results_history_router
from apps.compares.api.compare_method_results_history import compare_method_results_history_router
from apps.compares.api.compare_method_with_scenario import compare_method_with_scenario_router
from apps.compares.api.compare_result_with_averages import compare_result_with_averages_router
from apps.compares.api.compare_result_with_results import compare_result_with_results_router
from apps.compares.api.compare_result_with_scenario import compare_result_with_scenario_router
from apps.compares.api.compare_settings import compare_settings_router

compares_app_router = APIRouter()
compares_app_router.include_router(compare_settings_router)
compares_app_router.include_router(compare_result_with_results_router)
compares_app_router.include_router(compare_result_with_averages_router)
compares_app_router.include_router(compare_result_with_scenario_router)
compares_app_router.include_router(compare_method_with_scenario_router)
compares_app_router.include_router(compare_averages_with_scenario_router)
compares_app_router.include_router(compare_method_results_history_router)
compares_app_router.include_router(compare_load_test_results_history_router)
