"""base_models

Revision ID: 0f07834dd410
Revises: e291761da9cb
Create Date: 2024-12-28 21:45:35.726872

"""
from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = '0f07834dd410'
down_revision: Union[str, None] = 'e291761da9cb'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        'load_test_results',
        sa.Column('number_of_requests', sa.Integer(), nullable=False, server_default='0')
    )
    op.add_column(
        'load_test_results',
        sa.Column('number_of_failures', sa.Integer(), nullable=False, server_default='0')
    )
    op.add_column(
        'load_test_results',
        sa.Column('requests_per_second', sa.Float(), nullable=False, server_default='0.0')
    )
    op.add_column(
        'load_test_results',
        sa.Column('failures_per_second', sa.Float(), nullable=False, server_default='0.0')
    )

    op.execute(sa.text('UPDATE load_test_results SET number_of_requests = total_requests;'))
    op.execute(sa.text('UPDATE load_test_results SET number_of_failures = total_failures;'))
    op.execute(sa.text('UPDATE load_test_results SET requests_per_second = total_requests_per_second;'))
    op.execute(sa.text('UPDATE load_test_results SET failures_per_second = total_failures_per_second;'))

    op.add_column(
        'scenario_settings',
        sa.Column('response_time_percentile_50', sa.Float(), nullable=False, server_default='0.0')
    )
    op.add_column(
        'scenario_settings',
        sa.Column('response_time_percentile_60', sa.Float(), nullable=False, server_default='0.0')
    )
    op.add_column(
        'scenario_settings',
        sa.Column('response_time_percentile_70', sa.Float(), nullable=False, server_default='0.0')
    )
    op.add_column(
        'scenario_settings',
        sa.Column('response_time_percentile_80', sa.Float(), nullable=False, server_default='0.0')
    )
    op.add_column(
        'scenario_settings',
        sa.Column('response_time_percentile_90', sa.Float(), nullable=False, server_default='0.0')
    )
    op.add_column(
        'scenario_settings',
        sa.Column('response_time_percentile_95', sa.Float(), nullable=False, server_default='0.0')
    )
    op.add_column(
        'scenario_settings',
        sa.Column('response_time_percentile_99', sa.Float(), nullable=False, server_default='0.0')
    )
    op.add_column(
        'scenario_settings',
        sa.Column('response_time_percentile_100', sa.Float(), nullable=False, server_default='0.0')
    )
    op.add_column(
        'scenario_settings',
        sa.Column('median_response_time', sa.Float(), nullable=False, server_default='0.0')
    )

    op.alter_column(
        'scenario_settings',
        'number_of_requests',
        existing_type=sa.DOUBLE_PRECISION(precision=53),
        type_=sa.Integer(),
        existing_nullable=False
    )
    op.alter_column(
        'scenario_settings',
        'number_of_failures',
        existing_type=sa.DOUBLE_PRECISION(precision=53),
        type_=sa.Integer(),
        existing_nullable=False
    )
    op.alter_column(
        'scenario_settings',
        'number_of_users',
        existing_type=sa.DOUBLE_PRECISION(precision=53),
        type_=sa.Integer(),
        existing_nullable=False
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        'scenario_settings',
        'number_of_users',
        existing_type=sa.Integer(),
        type_=sa.DOUBLE_PRECISION(precision=53),
        existing_nullable=False
    )
    op.alter_column(
        'scenario_settings',
        'number_of_failures',
        existing_type=sa.Integer(),
        type_=sa.DOUBLE_PRECISION(precision=53),
        existing_nullable=False
    )
    op.alter_column(
        'scenario_settings',
        'number_of_requests',
        existing_type=sa.Integer(),
        type_=sa.DOUBLE_PRECISION(precision=53),
        existing_nullable=False
    )
    op.drop_column('scenario_settings', 'median_response_time')
    op.drop_column('scenario_settings', 'response_time_percentile_100')
    op.drop_column('scenario_settings', 'response_time_percentile_99')
    op.drop_column('scenario_settings', 'response_time_percentile_95')
    op.drop_column('scenario_settings', 'response_time_percentile_90')
    op.drop_column('scenario_settings', 'response_time_percentile_80')
    op.drop_column('scenario_settings', 'response_time_percentile_70')
    op.drop_column('scenario_settings', 'response_time_percentile_60')
    op.drop_column('scenario_settings', 'response_time_percentile_50')
    op.drop_column('load_test_results', 'failures_per_second')
    op.drop_column('load_test_results', 'requests_per_second')
    op.drop_column('load_test_results', 'number_of_failures')
    op.drop_column('load_test_results', 'number_of_requests')
    # ### end Alembic commands ###
