"""scenario_settings

Revision ID: 17d92fb2946b
Revises: fac12c553430
Create Date: 2024-08-05 20:21:58.268169

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '17d92fb2946b'
down_revision: Union[str, None] = 'fac12c553430'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('scenario_settings',
    sa.Column('max_response_time', sa.Float(), nullable=False),
    sa.Column('number_of_requests', sa.Float(), nullable=False),
    sa.Column('requests_per_second', sa.Float(), nullable=False),
    sa.Column('average_response_time', sa.Float(), nullable=False),
    sa.Column('methods_settings', sa.JSON(), nullable=False),
    sa.Column('scenario', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['scenario'], ['scenarios.name'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('scenario')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('scenario_settings')
    # ### end Alembic commands ###
