"""remove_legacy_columns

Revision ID: 21d3966e12ae
Revises: 0f07834dd410
Create Date: 2024-12-28 21:59:15.703060

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '21d3966e12ae'
down_revision: Union[str, None] = '0f07834dd410'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('load_test_results', 'total_requests_per_second')
    op.drop_column('load_test_results', 'total_failures_per_second')
    op.drop_column('load_test_results', 'total_requests')
    op.drop_column('load_test_results', 'total_failures')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('load_test_results', sa.Column('total_failures', sa.INTEGER(), autoincrement=False, nullable=False))
    op.add_column('load_test_results', sa.Column('total_requests', sa.INTEGER(), autoincrement=False, nullable=False))
    op.add_column('load_test_results', sa.Column('total_failures_per_second', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=False))
    op.add_column('load_test_results', sa.Column('total_requests_per_second', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=False))
    # ### end Alembic commands ###
