"""status_model

Revision ID: 4a2787d4b741
Revises: 8e173dbe7c2a
Create Date: 2024-12-06 11:48:23.283622

"""
from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

from services.postgres.models.base.status import ModelStatus

# revision identifiers, used by Alembic.
revision: str = '4a2787d4b741'
down_revision: Union[str, None] = '8e173dbe7c2a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        'load_test_results',
        sa.Column('status', sa.String(length=50), nullable=False, server_default=ModelStatus.ACTIVE)
    )
    op.add_column(
        'scenarios',
        sa.Column('status', sa.String(length=50), nullable=False, server_default=ModelStatus.ACTIVE)
    )
    op.add_column(
        'services',
        sa.Column('status', sa.String(length=50), nullable=False, server_default=ModelStatus.ACTIVE)
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('services', 'status')
    op.drop_column('scenarios', 'status')
    op.drop_column('load_test_results', 'status')
    # ### end Alembic commands ###
