"""scenarios_model

Revision ID: 4b9a85b1a0f7
Revises: a18f6233d444
Create Date: 2024-12-04 09:46:27.352491

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision: str = '4b9a85b1a0f7'
down_revision: Union[str, None] = 'a18f6233d444'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('scenarios',
                    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
                    sa.Column('tags', sa.JSON(), nullable=False),
                    sa.Column('name', sa.String(length=100), nullable=False),
                    sa.Column('file', sa.String(length=250), nullable=False),
                    sa.Column('version', sa.String(length=50), nullable=False),
                    sa.Column('ratio_total', sa.JSON(), nullable=False),
                    sa.Column('ratio_per_class', sa.JSON(), nullable=False),
                    sa.Column('service_id', sa.Integer(), nullable=False),
                    sa.ForeignKeyConstraint(['service_id'], ['services.id'], ondelete='CASCADE'),
                    sa.PrimaryKeyConstraint('id')
                    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('scenarios')
    # ### end Alembic commands ###
