"""percentiles

Revision ID: 4d47a5d62634
Revises: ef4e7bd75aed
Create Date: 2024-12-27 16:24:10.302328

"""
from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = '4d47a5d62634'
down_revision: Union[str, None] = 'ef4e7bd75aed'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        'history_results',
        sa.Column('min_response_time', sa.Float(), nullable=False, server_default='0.0')
    )
    op.add_column(
        'history_results',
        sa.Column('max_response_time', sa.Float(), nullable=False, server_default='0.0')
    )
    op.add_column(
        'history_results',
        sa.Column('number_of_requests', sa.Integer(), nullable=False, server_default='0')
    )
    op.add_column(
        'history_results',
        sa.Column('number_of_failures', sa.Integer(), nullable=False, server_default='0')
    )
    op.add_column(
        'history_results',
        sa.Column('median_response_time', sa.Float(), nullable=False, server_default='0.0')
    )
    op.add_column(
        'history_results',
        sa.Column('average_content_length', sa.Float(), nullable=False, server_default='0.0')
    )
    op.add_column(
        'history_results',
        sa.Column('response_time_percentile_50', sa.Float(), nullable=False, server_default='0.0')
    )
    op.add_column(
        'history_results',
        sa.Column('response_time_percentile_60', sa.Float(), nullable=False, server_default='0.0')
    )
    op.add_column(
        'history_results',
        sa.Column('response_time_percentile_70', sa.Float(), nullable=False, server_default='0.0')
    )
    op.add_column(
        'history_results',
        sa.Column('response_time_percentile_80', sa.Float(), nullable=False, server_default='0.0')
    )
    op.add_column(
        'history_results',
        sa.Column('response_time_percentile_90', sa.Float(), nullable=False, server_default='0.0')
    )
    op.add_column(
        'history_results',
        sa.Column('response_time_percentile_99', sa.Float(), nullable=False, server_default='0.0')
    )
    op.add_column(
        'history_results',
        sa.Column('response_time_percentile_100', sa.Float(), nullable=False, server_default='0.0')
    )

    op.add_column(
        'method_results',
        sa.Column('response_time_percentile_50', sa.Float(), nullable=False, server_default='0.0')
    )
    op.add_column(
        'method_results',
        sa.Column('response_time_percentile_60', sa.Float(), nullable=False, server_default='0.0')
    )
    op.add_column(
        'method_results',
        sa.Column('response_time_percentile_70', sa.Float(), nullable=False, server_default='0.0')
    )
    op.add_column(
        'method_results',
        sa.Column('response_time_percentile_80', sa.Float(), nullable=False, server_default='0.0')
    )
    op.add_column(
        'method_results',
        sa.Column('response_time_percentile_90', sa.Float(), nullable=False, server_default='0.0')
    )
    op.add_column(
        'method_results',
        sa.Column('response_time_percentile_95', sa.Float(), nullable=False, server_default='0.0')
    )
    op.add_column(
        'method_results',
        sa.Column('response_time_percentile_99', sa.Float(), nullable=False, server_default='0.0')
    )
    op.add_column(
        'method_results',
        sa.Column('response_time_percentile_100', sa.Float(), nullable=False, server_default='0.0')
    )
    op.drop_column('method_results', 'total_response_time')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('method_results',
                  sa.Column('total_response_time', sa.DOUBLE_PRECISION(precision=53), autoincrement=False,
                            nullable=False))
    op.drop_column('method_results', 'response_time_percentile_100')
    op.drop_column('method_results', 'response_time_percentile_99')
    op.drop_column('method_results', 'response_time_percentile_95')
    op.drop_column('method_results', 'response_time_percentile_90')
    op.drop_column('method_results', 'response_time_percentile_80')
    op.drop_column('method_results', 'response_time_percentile_70')
    op.drop_column('method_results', 'response_time_percentile_60')
    op.drop_column('method_results', 'response_time_percentile_50')
    op.drop_column('history_results', 'response_time_percentile_100')
    op.drop_column('history_results', 'response_time_percentile_99')
    op.drop_column('history_results', 'response_time_percentile_90')
    op.drop_column('history_results', 'response_time_percentile_80')
    op.drop_column('history_results', 'response_time_percentile_70')
    op.drop_column('history_results', 'response_time_percentile_60')
    op.drop_column('history_results', 'response_time_percentile_50')
    op.drop_column('history_results', 'average_content_length')
    op.drop_column('history_results', 'median_response_time')
    op.drop_column('history_results', 'number_of_failures')
    op.drop_column('history_results', 'number_of_requests')
    op.drop_column('history_results', 'max_response_time')
    op.drop_column('history_results', 'min_response_time')
    # ### end Alembic commands ###
