"""integration_model_order_index

Revision ID: 6cf84844e624
Revises: 7567c2f55977
Create Date: 2025-01-18 00:29:33.097400

"""
from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = '6cf84844e624'
down_revision: Union[str, None] = '7567c2f55977'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        'integrations',
        sa.Column('order_index', sa.Integer(), nullable=False, server_default='0')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('integrations', 'order_index')
    # ### end Alembic commands ###
