"""integration_model_url_template

Revision ID: 7567c2f55977
Revises: d9db27b8c6c3
Create Date: 2025-01-17 22:16:58.292998

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7567c2f55977'
down_revision: Union[str, None] = 'd9db27b8c6c3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('integrations', sa.Column('system_type', sa.String(length=30), nullable=False))
    op.add_column('integrations', sa.Column('url_template', sa.Text(), nullable=False))
    op.drop_column('integrations', 'cluster')
    op.drop_column('integrations', 'namespace')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('integrations', sa.Column('namespace', sa.VARCHAR(length=250), autoincrement=False, nullable=False))
    op.add_column('integrations', sa.Column('cluster', sa.VARCHAR(length=100), autoincrement=False, nullable=False))
    op.drop_column('integrations', 'url_template')
    op.drop_column('integrations', 'system_type')
    # ### end Alembic commands ###
