"""services_model_type

Revision ID: 82e855042439
Revises: d667c1928d4e
Create Date: 2024-12-05 13:47:02.259227

"""
from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = '82e855042439'
down_revision: Union[str, None] = 'd667c1928d4e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('services', sa.Column('type', sa.String(length=50), nullable=False))
    op.drop_column('services', 'is_internal')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('services', sa.Column('is_internal', sa.BOOLEAN(), autoincrement=False, nullable=False))
    op.drop_column('services', 'type')
    # ### end Alembic commands ###
