"""is_internal_for_services

Revision ID: 837f4741dfa2
Revises: ec5cb87f60b8
Create Date: 2024-08-01 00:17:01.835862

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '837f4741dfa2'
down_revision: Union[str, None] = 'ec5cb87f60b8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('services', sa.Column('is_internal', sa.Boolean(), server_default='false', nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('services', 'is_internal')
    # ### end Alembic commands ###
