"""scenario_settings_model

Revision ID: 8676d677c0d1
Revises: 4b9a85b1a0f7
Create Date: 2024-12-04 09:47:04.188909

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8676d677c0d1'
down_revision: Union[str, None] = '4b9a85b1a0f7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('scenario_settings',
    sa.Column('response_time', sa.Float(), nullable=False),
    sa.Column('number_of_users', sa.Float(), nullable=False),
    sa.Column('min_response_time', sa.Float(), nullable=False),
    sa.Column('max_response_time', sa.Float(), nullable=False),
    sa.Column('number_of_requests', sa.Float(), nullable=False),
    sa.Column('number_of_failures', sa.Float(), nullable=False),
    sa.Column('requests_per_second', sa.Float(), nullable=False),
    sa.Column('failures_per_second', sa.Float(), nullable=False),
    sa.Column('methods_settings', sa.JSON(), nullable=False),
    sa.Column('scenario_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['scenario_id'], ['scenarios.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('scenario_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('scenario_settings')
    # ### end Alembic commands ###
