"""scenarios

Revision ID: 86a4c71a7f31
Revises: 9d951fdb7706
Create Date: 2024-08-02 15:04:19.362064

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '86a4c71a7f31'
down_revision: Union[str, None] = '9d951fdb7706'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('ratio_results_scenario_fkey', 'ratio_results', type_='foreignkey')
    op.drop_column('ratio_results', 'scenario')
    op.drop_column('ratio_results', 'created_at')
    op.add_column('scenarios', sa.Column('file', sa.String(length=250), nullable=False))
    op.add_column('scenarios', sa.Column('ratio_total', sa.JSON(), nullable=False))
    op.add_column('scenarios', sa.Column('ratio_per_class', sa.JSON(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('scenarios', 'ratio_per_class')
    op.drop_column('scenarios', 'ratio_total')
    op.drop_column('scenarios', 'file')
    op.add_column('ratio_results', sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False))
    op.add_column('ratio_results', sa.Column('scenario', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.create_foreign_key('ratio_results_scenario_fkey', 'ratio_results', 'scenarios', ['scenario'], ['name'], ondelete='CASCADE')
    # ### end Alembic commands ###
