"""create_trigger_load_tests_job_url

Revision ID: 8e173dbe7c2a
Revises: cab5755ff976
Create Date: 2024-12-06 00:10:54.912160

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8e173dbe7c2a'
down_revision: Union[str, None] = 'cab5755ff976'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('load_test_results', sa.Column('trigger_ci_job_url', sa.String(), nullable=True))
    op.add_column('load_test_results', sa.Column('load_tests_ci_job_url', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('load_test_results', 'load_tests_ci_job_url')
    op.drop_column('load_test_results', 'trigger_ci_job_url')
    # ### end Alembic commands ###
