"""scenarios

Revision ID: 9d951fdb7706
Revises: 837f4741dfa2
Create Date: 2024-08-02 14:21:07.563616

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9d951fdb7706'
down_revision: Union[str, None] = '837f4741dfa2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('scenarios',
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.PrimaryKeyConstraint('name')
    )
    op.add_column('load_test_results', sa.Column('scenario', sa.String(), nullable=True))
    op.create_foreign_key(None, 'load_test_results', 'scenarios', ['scenario'], ['name'], ondelete='CASCADE')
    op.add_column('method_results', sa.Column('scenario', sa.String(), nullable=True))
    op.create_foreign_key(None, 'method_results', 'scenarios', ['scenario'], ['name'], ondelete='CASCADE')
    op.add_column('ratio_results', sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False))
    op.add_column('ratio_results', sa.Column('scenario', sa.String(), nullable=True))
    op.create_foreign_key(None, 'ratio_results', 'scenarios', ['scenario'], ['name'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'ratio_results', type_='foreignkey')
    op.drop_column('ratio_results', 'scenario')
    op.drop_column('ratio_results', 'created_at')
    op.drop_constraint(None, 'method_results', type_='foreignkey')
    op.drop_column('method_results', 'scenario')
    op.drop_constraint(None, 'load_test_results', type_='foreignkey')
    op.drop_column('load_test_results', 'scenario')
    op.drop_table('scenarios')
    # ### end Alembic commands ###
