"""remove_trigger_ci_project_title

Revision ID: cab5755ff976
Revises: eb47c6bf6df7
Create Date: 2024-12-05 23:36:58.482694

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'cab5755ff976'
down_revision: Union[str, None] = 'eb47c6bf6df7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('load_test_results', 'trigger_ci_project_title')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('load_test_results', sa.Column('trigger_ci_project_title', sa.VARCHAR(), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
