"""compare_settings_model

Revision ID: d8bad386e709
Revises: 8676d677c0d1
Create Date: 2024-12-04 09:50:15.776700

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd8bad386e709'
down_revision: Union[str, None] = '8676d677c0d1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('compare_settings',
    sa.Column('response_time_weight', sa.Float(), nullable=False),
    sa.Column('min_response_time_weight', sa.Float(), nullable=False),
    sa.Column('max_response_time_weight', sa.Float(), nullable=False),
    sa.Column('number_of_requests_weight', sa.Float(), nullable=False),
    sa.Column('number_of_failures_weight', sa.Float(), nullable=False),
    sa.Column('requests_per_second_weight', sa.Float(), nullable=False),
    sa.Column('failures_per_second_weight', sa.Float(), nullable=False),
    sa.Column('service_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['service_id'], ['services.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('service_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('compare_settings')
    # ### end Alembic commands ###
