"""scenario_settings

Revision ID: dd41704703e5
Revises: 17d92fb2946b
Create Date: 2024-08-05 22:19:38.695635

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision: str = 'dd41704703e5'
down_revision: Union[str, None] = '17d92fb2946b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('scenario_settings', 'number_of_requests')
    op.drop_column('scenario_settings', 'max_response_time')
    op.drop_column('scenario_settings', 'average_response_time')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('scenario_settings',
                  sa.Column('average_response_time', sa.DOUBLE_PRECISION(precision=53), autoincrement=False,
                            nullable=False))
    op.add_column('scenario_settings',
                  sa.Column('max_response_time', sa.DOUBLE_PRECISION(precision=53), autoincrement=False,
                            nullable=False))
    op.add_column('scenario_settings',
                  sa.Column('number_of_requests', sa.DOUBLE_PRECISION(precision=53), autoincrement=False,
                            nullable=False))
    # ### end Alembic commands ###
