"""create_scenario_settings_average_response_time

Revision ID: e291761da9cb
Revises: 375fa137c333
Create Date: 2024-12-28 19:27:33.883480

"""
from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = 'e291761da9cb'
down_revision: Union[str, None] = '375fa137c333'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        'scenario_settings',
        sa.Column('average_response_time', sa.Float(), nullable=False, server_default='0.0')
    )
    op.drop_column('scenario_settings', 'response_time')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        'scenario_settings',
        sa.Column('response_time', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=False)
    )
    op.drop_column('scenario_settings', 'average_response_time')
    # ### end Alembic commands ###
