"""scenario_settings_model_highligh_threshold

Revision ID: e5afd911905e
Revises: 27e02fcc2723
Create Date: 2024-12-20 21:04:20.006462

"""
import json
from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

from services.postgres.models.compare_settings import get_default_compare_settings_weights_dict, \
    get_default_compare_settings_highlight_threshold_dict

# revision identifiers, used by Alembic.
revision: str = 'e5afd911905e'
down_revision: Union[str, None] = '27e02fcc2723'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        'compare_settings',
        sa.Column(
            'weights',
            sa.JSON(),
            nullable=False,
            server_default=json.dumps(get_default_compare_settings_weights_dict())
        )
    )
    op.add_column(
        'compare_settings',
        sa.Column(
            'highlight_threshold',
            sa.JSON(),
            nullable=False,
            server_default=json.dumps(get_default_compare_settings_highlight_threshold_dict())
        )
    )
    op.drop_column('compare_settings', 'failures_per_second_weight')
    op.drop_column('compare_settings', 'number_of_requests_weight')
    op.drop_column('compare_settings', 'max_response_time_weight')
    op.drop_column('compare_settings', 'min_response_time_weight')
    op.drop_column('compare_settings', 'requests_per_second_weight')
    op.drop_column('compare_settings', 'response_time_weight')
    op.drop_column('compare_settings', 'number_of_failures_weight')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('compare_settings',
                  sa.Column('number_of_failures_weight', sa.DOUBLE_PRECISION(precision=53), autoincrement=False,
                            nullable=False))
    op.add_column('compare_settings',
                  sa.Column('response_time_weight', sa.DOUBLE_PRECISION(precision=53), autoincrement=False,
                            nullable=False))
    op.add_column('compare_settings',
                  sa.Column('requests_per_second_weight', sa.DOUBLE_PRECISION(precision=53), autoincrement=False,
                            nullable=False))
    op.add_column('compare_settings',
                  sa.Column('min_response_time_weight', sa.DOUBLE_PRECISION(precision=53), autoincrement=False,
                            nullable=False))
    op.add_column('compare_settings',
                  sa.Column('max_response_time_weight', sa.DOUBLE_PRECISION(precision=53), autoincrement=False,
                            nullable=False))
    op.add_column('compare_settings',
                  sa.Column('number_of_requests_weight', sa.DOUBLE_PRECISION(precision=53), autoincrement=False,
                            nullable=False))
    op.add_column('compare_settings',
                  sa.Column('failures_per_second_weight', sa.DOUBLE_PRECISION(precision=53), autoincrement=False,
                            nullable=False))
    op.drop_column('compare_settings', 'highlight_threshold')
    op.drop_column('compare_settings', 'weights')
    # ### end Alembic commands ###
