"""remove_service_type

Revision ID: ef4e7bd75aed
Revises: b57a5ea527b6
Create Date: 2024-12-26 13:35:16.888956

"""
from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = 'ef4e7bd75aed'
down_revision: Union[str, None] = 'b57a5ea527b6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('services', 'type')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        'services',
        sa.Column(
            'type',
            sa.VARCHAR(length=50),
            erver_default=sa.text("'PRODUCTION'::character varying"),
            autoincrement=False,
            nullable=False
        )
    )
    # ### end Alembic commands ###
