"""create_scenarios_number_of_users_and_runtime_duration

Revision ID: f75f5a50cb52
Revises: 8e51a8beed4d
Create Date: 2025-01-03 13:00:53.520680

"""
from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = 'f75f5a50cb52'
down_revision: Union[str, None] = '8e51a8beed4d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        'scenarios',
        sa.Column('number_of_users', sa.Integer(), nullable=False, server_default='0')
    )
    op.add_column(
        'scenarios',
        sa.Column('runtime_duration', sa.String(length=50), nullable=False, server_default='0s')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('scenarios', 'runtime_duration')
    op.drop_column('scenarios', 'number_of_users')
    # ### end Alembic commands ###
